### ISSUE TITLE
Failed to compile with GCC10

### ISSUE THREAD

**Issue by runlevel5** [libnxz/power-gzip#35] opened 2020-06-27 12:52 UTC
[GCC10 Default to -fno-common](https://gcc.gnu.org/gcc-10/porting_to.html) caused compilation errors:

```
$ make
gcc -std=gnu11 -O3 -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN -DZLIB_API -mcpu=power9  -I./inc_nx -c nx_inflate.c nx_deflate.c nx_zlib.c nx_crc.c nx_dht.c nx_dhtgen.c nx_dht_builtin.c nx_adler32.c gzip_vas.c nx_compress.c nx_uncompr.c crc32_ppc.c crc32_ppc_asm.S
rm -f libnxz.a
ar rcs -o libnxz.a nx_inflate.o nx_deflate.o nx_zlib.o nx_crc.o nx_dht.o nx_dhtgen.o nx_dht_builtin.o nx_adler32.o gzip_vas.o nx_compress.o nx_uncompr.o crc32_ppc.o crc32_ppc_asm.o
rm -f libnxz.so
gcc -shared  -Wl,-soname,libnxz.so,--version-script,zlib.map -o libnxz.so nx_inflate.o nx_deflate.o nx_zlib.o nx_crc.o nx_dht.o nx_dhtgen.o nx_dht_builtin.o nx_adler32.o gzip_vas.o nx_compress.o nx_uncompr.o crc32_ppc.o crc32_ppc_asm.o	
/usr/bin/ld: nx_deflate.o:(.bss+0x0): multiple definition of `mutex_log'; nx_inflate.o:(.bss+0x0): first defined here
/usr/bin/ld: nx_zlib.o:(.bss+0x8228): multiple definition of `mutex_log'; nx_inflate.o:(.bss+0x0): first defined here
/usr/bin/ld: gzip_vas.o:(.bss+0x18): multiple definition of `mutex_log'; nx_inflate.o:(.bss+0x0): first defined here
/usr/bin/ld: nx_compress.o:(.bss+0x0): multiple definition of `mutex_log'; nx_inflate.o:(.bss+0x0): first defined here
/usr/bin/ld: nx_uncompr.o:(.bss+0x0): multiple definition of `mutex_log'; nx_inflate.o:(.bss+0x0): first defined here
```

The fix is quite trivial by using `extern` for `mutex_log` in header file and declare the variable in C file. Here is [one example](https://github.com/rednex/rgbds/pull/504)

**Comment by tuliom** [comment] 2020-06-27 18:52
This is a duplicate of issue #3. It's already fixed in branch develop.

**Closed** 2020-06-27 18:56 UTC
Labels: duplicate
